version: '3.7'

services:
  mongo_store:
    image: mongo:latest
    container_name: "mongo_store"
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: none
  redis_store:
    image: redis:latest
    container_name: "redis_store"
    restart: always
    ports:
      - "6379:6379"
    logging:
      driver: none